# Generated by Django 5.1.6 on 2025-04-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('magnet_link', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('last_watched', models.DateTimeField(blank=True, null=True)),
                ('download_status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('READY', 'Ready'), ('CONVERTING', 'Converting'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('download_progress', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
