# Generated by Django 5.1.6 on 2025-04-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_moviefile_delete_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieFile',
        ),
    ]
