# Generated by Django 5.1.6 on 2025-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_moviefile_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='total_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='download_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='tmdb_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
