# Generated by Django 5.1.6 on 2025-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviefile_total_duration_moviefile_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviefile',
            name='total_duration',
        ),
        migrations.RemoveField(
            model_name='moviefile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='download_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('READY', 'Ready'), ('ERROR', 'Error'), ('CONVERTING', 'Converting')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='moviefile',
            name='tmdb_id',
            field=models.IntegerField(),
        ),
    ]
