# Generated by Django 5.1.6 on 2025-04-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_delete_moviefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
