# Generated by Django 5.1.6 on 2025-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_moviefile_total_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
