# Generated by Django 5.1.6 on 2025-05-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieFile',
        ),
    ]
