# Generated by Django 5.1.6 on 2025-06-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_remove_moviefile_total_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_id', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('download_count', models.IntegerField(default=0)),
                ('hearing_impaired', models.BooleanField(default=False)),
                ('hd', models.BooleanField(default=False)),
                ('fps', models.FloatField(null=True)),
                ('ratings', models.FloatField(default=0)),
                ('from_trusted', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField()),
                ('release', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.moviefile')),
            ],
            options={
                'ordering': ['-ratings', '-download_count'],
                'unique_together': {('movie', 'subtitle_id', 'language')},
            },
        ),
    ]
