# Generated by Django 5.1.6 on 2025-02-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('42', '42')], default='email', max_length=50),
        ),
    ]
